import Head from "next/head";
import "@/styles/globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
export default function App({ Component, pageProps }) {
  return (
    <div className="body px-4">
      <Head>
        <title>CRM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;0,600;0,700;0,800;1,200;1,300&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="">
        <Header />
        <Component {...pageProps} />
        <Footer />
      </div>
    </div>
  );
}
